name: pattern_recognition_env
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=2.1.2
  - numpy=1.21.5
  - requests=2.32.5
  - python=3.9.24
  - scipy=1.10.1
  - scikit-learn=1.3.0
  - scikit-image=0.21.0
  - torch==1.12.0
  - torchvision==0.13.0
